Add vagrant-box targets to Makefile

diff --git a/scripts/Makefile b/scripts/Makefile
--- a/scripts/Makefile
+++ b/scripts/Makefile
@@ -111,7 +111,7 @@ local_login          := $(shell jq '.localLogin' $(cluster_details_file) | sed '
 # PROVISIONER CONFIG
 prov_hostname_base   := $(shell jq '.nodeGroups[] | select(.nodeGroup == "provisioner") | .hostnameBase?' $(cluster_details_file) | sed 's/\"//g' )
 prov_addr_start      := $(shell jq '.nodeGroups[] | select(.nodeGroup == "provisioner") | .addrStart?' $(cluster_details_file) | sed 's/\"//g' )
-provisioner_hostname := $(prov_hostname_base)-$(prov_addr_start)
+prov_hostname        := $(prov_hostname_base)-$(prov_addr_start)
 # APPLIANCE CONFIG
 app_hostname_base    := $(shell jq '.nodeGroups[] | select(.nodeGroup == "appliance") | .hostnameBase?' $(cluster_details_file) | sed 's/\"//g' )
 app_addr_start       := $(shell jq '.nodeGroups[] | select(.nodeGroup == "appliance") | .addrStart?'    $(cluster_details_file) | sed 's/\"//g' )
@@ -166,7 +166,7 @@ vagrant-up: load-node-data
 	echo "## Extracting SSH config to file: $(ssh_config_file)" &&\
 	echo "#################################################" &&\
 	mkdir -p target &&\
-	env_name=$(env_name) vagrant ssh-config $(provisioner_hostname) > $(ssh_config_file) \
+	env_name=$(env_name) vagrant ssh-config $(prov_hostname) > $(ssh_config_file) \
 	) || exit 1
 
 # Run just the ansible provisioning on the jumpbox VM
@@ -175,10 +175,10 @@ vagrant-up: load-node-data
 vagrant-reload: load-node-data
 	$(quiet) time ( \
 	( if [[ ! -e $(ssh_config_file) ]]; then echo "Run 'make vagrant-up' to generate ssh connection file: $(ssh_config_file)" && exit 1; fi ) &&\
-	ssh -F $(ssh_config_file) $(provisioner_hostname) \
+	ssh -F $(ssh_config_file) $(prov_hostname) \
 	"if [[ ! -e /etc/ansible/linux-provisioner ]]; then \
 		sudo -u $(local_login) bash -c \
-			'ssh-keyscan $(provisioner_hostname) | grep ecdsa-sha2 > ~$(local_login)/.ssh/known_hosts && chmod 600 ~$(local_login)/.ssh/known_hosts' &&\
+			'ssh-keyscan $(prov_hostname) | grep ecdsa-sha2 > ~$(local_login)/.ssh/known_hosts && chmod 600 ~$(local_login)/.ssh/known_hosts' &&\
 		if [[ $(app_node_count) -gt 0 ]]; then \
 			app_node_max=$$(( $(app_node_count) - 1 )) &&\
 			app_node_seq=\$$(seq 0 \$${app_node_max}); \
@@ -191,11 +191,131 @@ vagrant-reload: load-node-data
 		fi \
 	fi" &&\
 	echo "#################################################" &&\
-	echo "## Running 'vagrant reload --provision $(provisioner_hostname)" &&\
+	echo "## Running 'vagrant reload --provision $(prov_hostname)" &&\
 	echo "#################################################" &&\
-	debug=$(debug) env_name=$(env_name) vagrant reload --provision $(provisioner_hostname) \
+	debug=$(debug) env_name=$(env_name) vagrant reload --provision $(prov_hostname) \
 	) || exit 1
 
+.PHONY: vagrant-box-setup
+vagrant-box-setup:
+BUILD_NUMBER ?= 0
+# SETUP FOR VAGRANT_UPLOAD
+artifactory_base_url := artifactory.local.example.com/artifactory
+vagrant_repo_url := $(artifactory_base_url)/vagrant-local
+vagrant_api_url := $(artifactory_base_url)/api/vagrant
+vagrant_server_url := https://$(vagrant_api_url)/vagrant-local
+vagrant_auth_url := $(vagrant_api_url)/auth
+# SETUP FOR vagrant-box-upload and vagrant-box-download
+ifeq ($(VAGRANT_MACHINE_TYPE),appliance)
+  vagrant_upload_url := https://$(vagrant_repo_url)/boxes/$(app_hostname_base)/versions/$(app_build_version)/providers/$(vm_provider).box
+  vagrant_download_url := https://$(vagrant_repo_url)/boxes/$(app_image_name)/versions/$(app_image_version)/providers/$(vm_provider).box
+  image_name := $(app_image_name)
+  hostname_base := $(app_hostname_base)
+  vm_hostname := $(app_hostname)
+  download_version := $(app_image_version)
+  os_family := $(app_os_family)
+  ifdef BUILD_NUMBER
+    upload_version := $(app_build_version).$(BUILD_NUMBER)
+  else
+    upload_version := $(app_build_version).0
+  endif
+else
+  vagrant_upload_url := https://$(vagrant_repo_url)/boxes/$(pro_hostname_base)/versions/$(pro_build_version)/providers/$(vm_provider).box
+  vagrant_download_url := https://$(vagrant_repo_url)/boxes/$(pro_image_name)/versions/$(pro_image_version)/providers/$(vm_provider).box
+  image_name := $(pro_image_name)
+  hostname_base := $(pro_hostname_base)
+  vm_hostname := $(pro_hostname)
+  download_version := $(pro_image_version)
+  os_family := $(pro_os_family)
+  ifdef BUILD_NUMBER
+    upload_version := $(pro_build_version).$(BUILD_NUMBER)
+  else
+    upload_version := $(pro_build_version).0
+  endif
+endif
+
+.PHONY: vagrant-bootstrap-check
+vagrant-bootstrap-check:
+ifeq (, $(shell which jq))
+	echo "Install missing tool 'jq'" &&\
+	echo "  Windows: choco install jq" &&\
+	echo "   CentOS: make linux-bootstrap" &&\
+	exit 1
+endif
+
+# DEVELOPMENT: Package the local VM into a vagrant box file.
+# Used by make targets: vagrant-box-cache
+.PHONY: vagrant-box-package
+vagrant-box-package:  vagrant-box-setup vagrant-bootstrap-check
+ifndef hostname_base
+	$(error VAGRANT_MACHINE_TYPE=$(VAGRANT_MACHINE_TYPE) results in an empty hostname_base)
+endif
+	$(HIDE_CMD) VAGRANT_BOX_NAME=$(hostname_base)-$(vm_provider)-0.box &&\
+	rm -f target/$${VAGRANT_BOX_NAME} &&\
+	echo "$(VAGRANT_MACHINE_TYPE): Packaging vagrant box: $(vm_hostname) --> target/$${VAGRANT_BOX_NAME}" &&\
+	vagrant package --output target/$${VAGRANT_BOX_NAME} $(vm_hostname)
+	
+# DEVELOPMENT: Add a vagrant box package to the local vagrant cache
+# Used by make targets: vagrant-box-cache
+.PHONY: vagrant-box-add
+vagrant-box-add:  vagrant-box-setup vagrant-bootstrap-check
+ifndef hostname_base
+	$(error VAGRANT_MACHINE_TYPE=$(VAGRANT_MACHINE_TYPE) results in an empty hostname_base)
+endif
+ifneq (,$(image_name))
+	$(HIDE_CMD) VAGRANT_BOX_NAME=$(hostname_base)-$(vm_provider)-0.box &&\
+	INSTALLED_BOX_COUNT=`vagrant box list | grep "$(hostname_base).*($(vm_provider), 0)" | wc -l` &&\
+	if [[ $${INSTALLED_BOX_COUNT} -eq 0 ]]; then \
+		echo "$(VAGRANT_MACHINE_TYPE): Adding the vagrant box image: $(hostname_base):0" &&\
+		vagrant box add --name $(hostname_base) target/$${VAGRANT_BOX_NAME} ; \
+	else \
+		echo "$(VAGRANT_MACHINE_TYPE): Found cached Vagrant box image for the $(VAGRANT_MACHINE_TYPE): $(hostname_base):0" &&\
+		echo "$(VAGRANT_MACHINE_TYPE): To remove cached Vagrant box image: vagrant box remove --box-version 0 --provider $(vm_provider) $(hostname_base)" &&\
+		exit 1; \
+	fi
+endif
+
+# DEVELOPMENT: Add a vagrant box package to the local vagrant cache
+.PHONY: vagrant-box-cache
+vagrant-box-cache:  vagrant-box-setup vagrant-bootstrap-check vagrant-box-package vagrant-box-add
+	$(HIDE_CMD)echo "$(VAGRANT_MACHINE_TYPE): Cached Vagrant box image for $(VAGRANT_MACHINE_TYPE): $(hostname_base):0"; \
+
+# Download parent vagrant box from the artifactory vagrant repo
+.PHONY: vagrant-box-download
+vagrant-box-download: vagrant-box-setup vagrant-bootstrap-check
+ifneq (,$(app_image_name))
+	$(info APPLIANCE: Attempt to download VM image from: $(vagrant_app_download_url))
+	$(HIDE_CMD) INSTALLED_BOX_COUNT=`vagrant box list | grep "$(app_image_name).*$(vm_provider).*$(app_image_version)" | wc -l` &&\
+	if [[ $${INSTALLED_BOX_COUNT} -eq 0 ]]; then \
+		echo "APPLIANCE: Downloading the vagrant box image: $(app_image_name):$(app_image_version)" &&\
+		PASSWORD_FILE="target/.ansible_password_file" &&\
+		USER_LOGIN=devopssa &&\
+		USER_PASSWORD=`cat $${PASSWORD_FILE}` &&\
+		VAGRANT_BOX_URL="$(vagrant_server_url)/$(app_image_name)" &&\
+		VAGRANT_SERVER_URL=$(vagrant_server_url) \
+		ATLAS_TOKEN=`curl -s https://$${USER_LOGIN}:$${USER_PASSWORD}@$(vagrant_auth_url)` \
+		vagrant box add --name $(app_image_name) --box-version $(app_image_version) $${VAGRANT_BOX_URL}; \
+	else \
+		echo "APPLIANCE: Found cached Vagrant box image for the $(VAGRANT_MACHINE_TYPE): $(app_image_name):$(app_image_version)"; \
+	fi
+endif
+ifneq (,$(pro_image_name))
+	$(info PROVISIONER: Attempt to download VM image from: $(vagrant_pro_download_url))
+	$(HIDE_CMD) INSTALLED_BOX_COUNT=`vagrant box list | grep "$(pro_image_name).*$(vm_provider).*$(pro_image_version)" | wc -l` &&\
+	if [[ $${INSTALLED_BOX_COUNT} -eq 0 ]]; then \
+		echo "PROVISIONER: Downloading the vagrant box image: $(pro_image_name):$(pro_image_version)" &&\
+		PASSWORD_FILE="target/.ansible_password_file" &&\
+		USER_LOGIN=devopssa &&\
+		USER_PASSWORD=`cat $${PASSWORD_FILE}` &&\
+		VAGRANT_BOX_URL="$(vagrant_server_url)/$(pro_image_name)" &&\
+		VAGRANT_SERVER_URL=$(vagrant_server_url) \
+		ATLAS_TOKEN=`curl -s https://$${USER_LOGIN}:$${USER_PASSWORD}@$(vagrant_auth_url)` \
+		vagrant box add --name $(pro_image_name) --box-version $(pro_image_version) $${VAGRANT_BOX_URL}; \
+	else \
+		echo "PROVISIONER: Found cached Vagrant box image for the $(VAGRANT_MACHINE_TYPE): $(pro_image_name):$(pro_image_version)"; \
+	fi
+endif
+	
 # Setup ssh certs and ansible on the provisioner
 .PHONY: ansible-setup
 ansible-setup:
